train:
  activation: leaky_relu
  batch_size: 1024
  dataset: MNIST
  dropout: 0.1
  epochs: 10
  goodness: RootMeanSquare
  hidden_layers: 4
  hidden_units: 784
  input_dim: 784
  learning_rate: 0.003
  model_path: ./models
  optimizer: adam
  seed: 1
  threshold: 1.0
  trainer: Greedy
wandb:
  project: First-implementation-of-FFA
  run_name: test_3
